moai:
    initialized: true
    initialized_at: "2025-12-19T00:00:00Z"
    version: 1.14.5
project:
    created_at: "2026-01-18 13:27:40"
    description: ""
    mode: personal
    name: buy-dip-sell-peak-system
    optimized: false
    template_version: ""
