moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.11.2
project:
  name: buy-dip-sell-peak-system
  mode: personal
  description: ''
  created_at: '2026-01-18 13:27:40'
  optimized: false
  template_version: 1.11.2
